### ISSUE TITLE
pyspoa does not raise a Python exception when running out of memory

### ISSUE THREAD

**Issue by eldariont** [nanoporetech/pyspoa#6]
Hi,

thanks for providing this very helpful package. I'm using it to compute a consensus of (potentially) long sequences. As spoa's memory complexity is quadratic it can happen that I run out of memory on my machine. In that case, I would like to catch an exception and return a helpful error message. Something along the lines of:

```
try:
    cons, msa = poa(sequences)
except MemoryError:
    print("You ran out of memory. Use shorter sequences.")
```

However, pyspoa does not seem to raise a Python exception when running out of memory:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/bin/bash: line 1: 111186 Aborted                 (core dumped) ...
```

As pyspoa is using the pybind11 library, I read what they write about exceptions (https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html) and apparently, an `std::bad_alloc` exception should be translated to a python `MemoryError`. I have no idea why that did not work in my case.

Can you reproduce this issue and if yes, do you have an idea how I could catch an memory error in python?

Cheers
David

**Comment by iiSeymour** [comment]
Hey @eldariont 

Can you try [v0.0.6](https://github.com/nanoporetech/pyspoa/releases/tag/v0.0.6) which I just published - I now see Python exceptions thrown instead of segfaults.

**Comment by eldariont** [comment]
Hi Chris,

I tried v0.0.6 and indeed get an exception now 👍  It's a ValueError instead of a MemoryError but I can now catch it.

Thanks a lot!
David
