### ISSUE TITLE
Can't generate multiple consensus sequences

### ISSUE THREAD

**Issue by kcjavier21** [nanoporetech/pyspoa#7]
Hello! I want to generate more than one consensus sequence, but there seems to be no instruction for it.

Is there a way to do so? Thank you!

**Comment by cjw85** [comment]
Hi @kcjavier21,

Can you expand on your question? The entire functionality of this library is documented in that [usage](https://github.com/nanoporetech/pyspoa#usage) section of the README. This is a very simple library that exposes that functionality of the C++ spoa library to compute an MSA and a corresponding consensus.

**Comment by kcjavier21** [comment]
Hello! I've read this issue (https://github.com/rvaser/spoa/issues/12) from SPOA repo and it seems like they haven't implemented the said feature. Thanks anyway.
